-- MySQL Script generated by MySQL Workbench
-- 03/23/19 12:50:37
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema onlineshop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema onlineshop
-- -----------------------------------------------------
DROP DATABASE IF EXISTS `onlineshop`;
CREATE SCHEMA IF NOT EXISTS `onlineshop` DEFAULT CHARACTER SET utf8 ;
USE `onlineshop` ;

-- -----------------------------------------------------
-- Table `onlineshop`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `onlineshop`.`product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `price` INT UNSIGNED NOT NULL,
  `count` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC));


-- -----------------------------------------------------
-- Table `onlineshop`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `onlineshop`.`category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `parent_id` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_category_category1_idx` (`parent_id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  CONSTRAINT `fk_category_category1`
    FOREIGN KEY (`parent_id`)
    REFERENCES `onlineshop`.`category` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `onlineshop`.`product_has_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `onlineshop`.`product_has_category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `product_id` INT NOT NULL,
  `category_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_product_has_category_category1_idx` (`category_id` ASC),
  INDEX `fk_product_has_category_product_idx` (`product_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `fk_product_has_category_product`
    FOREIGN KEY (`product_id`)
    REFERENCES `onlineshop`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_has_category_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `onlineshop`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `onlineshop`.`account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `onlineshop`.`account` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `patronymic` VARCHAR(45) NULL,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `onlineshop`.`administrator`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `onlineshop`.`administrator` (
  `user_id` INT NOT NULL,
  `position` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`user_id`),
  INDEX `fk_administrator_user1_idx` (`user_id` ASC),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC),
  CONSTRAINT `fk_administrator_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `onlineshop`.`account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `onlineshop`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `onlineshop`.`client` (
  `user_id` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `phone_number_UNIQUE` (`phone` ASC),
  INDEX `fk_client_user1_idx` (`user_id` ASC),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC),
  CONSTRAINT `fk_client_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `onlineshop`.`account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `onlineshop`.`client_has_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `onlineshop`.`client_has_product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `client_user_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `price` INT UNSIGNED NOT NULL,
  `count` INT UNSIGNED NULL,
  INDEX `fk_product_has_basket_product1_idx` (`product_id` ASC),
  INDEX `fk_client_has_product_client1_idx` (`client_user_id` ASC),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `fk_product_has_basket_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `onlineshop`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_client_has_product_client1`
    FOREIGN KEY (`client_user_id`)
    REFERENCES `onlineshop`.`client` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `onlineshop`.`purchase`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `onlineshop`.`purchase` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `client_user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_purchase_client1_idx` (`client_user_id` ASC),
  CONSTRAINT `fk_purchase_client1`
    FOREIGN KEY (`client_user_id`)
    REFERENCES `onlineshop`.`client` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `onlineshop`.`purchase_has_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `onlineshop`.`purchase_has_product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `purchase_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `price` INT UNSIGNED NOT NULL,
  `count` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_product_has_purchase_purchase1_idx` (`purchase_id` ASC),
  INDEX `fk_product_has_purchase_product1_idx` (`product_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `fk_product_has_purchase_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `onlineshop`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_has_purchase_purchase1`
    FOREIGN KEY (`purchase_id`)
    REFERENCES `onlineshop`.`purchase` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `onlineshop`.`amount`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `onlineshop`.`amount` (
  `client_user_id` INT NOT NULL,
  `amount` INT ZEROFILL NOT NULL,
  PRIMARY KEY (`client_user_id`),
  UNIQUE INDEX `client_user_id_UNIQUE` (`client_user_id` ASC),
  CONSTRAINT `fk_account_client1`
    FOREIGN KEY (`client_user_id`)
    REFERENCES `onlineshop`.`client` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `onlineshop`.`session`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `onlineshop`.`session` (
  `cookie` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`cookie`),
  UNIQUE INDEX `cookie_UNIQUE` (`cookie` ASC),
  INDEX `fk_session_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_session_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `onlineshop`.`account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
