-- MySQL Script generated by MySQL Workbench
-- 05/03/19 01:43:50
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema onlineshop
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `onlineshop` ;

-- -----------------------------------------------------
-- Schema onlineshop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `onlineshop` DEFAULT CHARACTER SET utf8 ;
USE `onlineshop` ;

-- -----------------------------------------------------
-- Table `onlineshop`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `onlineshop`.`product` ;

CREATE TABLE IF NOT EXISTS `onlineshop`.`product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `price` INT UNSIGNED NOT NULL,
  `count` INT UNSIGNED NOT NULL,
  `version` INT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC));


-- -----------------------------------------------------
-- Table `onlineshop`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `onlineshop`.`category` ;

CREATE TABLE IF NOT EXISTS `onlineshop`.`category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `parent_id` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  INDEX `fk_category_category1_idx` (`parent_id` ASC),
  CONSTRAINT `fk_category_category1`
    FOREIGN KEY (`parent_id`)
    REFERENCES `onlineshop`.`category` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `onlineshop`.`product_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `onlineshop`.`product_category` ;

CREATE TABLE IF NOT EXISTS `onlineshop`.`product_category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `product_id` INT NOT NULL,
  `category_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_product_has_category_category1_idx` (`category_id` ASC),
  INDEX `fk_product_has_category_product_idx` (`product_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `fk_product_has_category_product`
    FOREIGN KEY (`product_id`)
    REFERENCES `onlineshop`.`product` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_has_category_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `onlineshop`.`category` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `onlineshop`.`account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `onlineshop`.`account` ;

CREATE TABLE IF NOT EXISTS `onlineshop`.`account` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `patronymic` VARCHAR(45) NULL,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `onlineshop`.`administrator`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `onlineshop`.`administrator` ;

CREATE TABLE IF NOT EXISTS `onlineshop`.`administrator` (
  `account_id` INT NOT NULL,
  `position` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`account_id`),
  INDEX `fk_administrator_user1_idx` (`account_id` ASC),
  UNIQUE INDEX `user_id_UNIQUE` (`account_id` ASC),
  CONSTRAINT `fk_administrator_user1`
    FOREIGN KEY (`account_id`)
    REFERENCES `onlineshop`.`account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `onlineshop`.`client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `onlineshop`.`client` ;

CREATE TABLE IF NOT EXISTS `onlineshop`.`client` (
  `account_id` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`account_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `phone_number_UNIQUE` (`phone` ASC),
  INDEX `fk_client_user1_idx` (`account_id` ASC),
  UNIQUE INDEX `user_id_UNIQUE` (`account_id` ASC),
  CONSTRAINT `fk_client_user1`
    FOREIGN KEY (`account_id`)
    REFERENCES `onlineshop`.`account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `onlineshop`.`product_in_basket`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `onlineshop`.`product_in_basket` ;

CREATE TABLE IF NOT EXISTS `onlineshop`.`product_in_basket` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `client_account_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `count` INT UNSIGNED NOT NULL,
  INDEX `fk_product_has_basket_product1_idx` (`product_id` ASC),
  INDEX `fk_client_has_product_client1_idx` (`client_account_id` ASC),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `fk_product_has_basket_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `onlineshop`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_client_has_product_client1`
    FOREIGN KEY (`client_account_id`)
    REFERENCES `onlineshop`.`client` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `onlineshop`.`product_in_purchase`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `onlineshop`.`product_in_purchase` ;

CREATE TABLE IF NOT EXISTS `onlineshop`.`product_in_purchase` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `client_account_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `price` INT UNSIGNED NOT NULL,
  `count` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_purchase_client1_idx` (`client_account_id` ASC),
  INDEX `fk_purchase_product1_idx` (`product_id` ASC),
  CONSTRAINT `fk_purchase_client1`
    FOREIGN KEY (`client_account_id`)
    REFERENCES `onlineshop`.`client` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_purchase_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `onlineshop`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `onlineshop`.`deposit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `onlineshop`.`deposit` ;

CREATE TABLE IF NOT EXISTS `onlineshop`.`deposit` (
  `client_account_id` INT NOT NULL,
  `deposit` INT NOT NULL,
  `version` INT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`client_account_id`),
  UNIQUE INDEX `client_user_id_UNIQUE` (`client_account_id` ASC),
  CONSTRAINT `fk_account_client1`
    FOREIGN KEY (`client_account_id`)
    REFERENCES `onlineshop`.`client` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `onlineshop`.`session`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `onlineshop`.`session` ;

CREATE TABLE IF NOT EXISTS `onlineshop`.`session` (
  `cookie` VARCHAR(45) NOT NULL,
  `account_id` INT NOT NULL ,
  PRIMARY KEY (`cookie`),
  UNIQUE INDEX `cookie_UNIQUE` (`cookie` ASC),
  UNIQUE INDEX `account_UNIQUE` (`account_id` ASC),
  INDEX `fk_session_user1_idx` (`account_id` ASC),
  CONSTRAINT `fk_session_user1`
    FOREIGN KEY (`account_id`)
    REFERENCES `onlineshop`.`account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;